version: "3.9"
services:
  redis:
    container_name: redis_kaboom
    image: "redislabs/redismod"
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    entrypoint:
      redis-server
        --loadmodule /usr/lib/redis/modules/rejson.so
        --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  node:
    container_name: node_kaboom
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run load && npm run dev"
    depends_on:
      - redis
    network_mode: "host"
